[meta]
name = "Bonk!"
author = "MisfitMaid"
category = "Audio"
version = "1.5.1"
siteid = 314

[script]
dependencies = ["VehicleState", "Camera"]
optional_dependencies = ["MLHook", "MLFeedRaceData"]
exports = ["Export.bonk.as"]
module = "bonk"
